# Generated by Django 3.0 on 2020-02-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='varaiables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField(blank=True, max_length=200, null=True)),
                ('y', models.TextField(blank=True, max_length=200, null=True)),
                ('operator', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
