# Generated by Django 3.0.1 on 2020-02-26 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_x', models.TextField(blank=True, max_length=200, null=True)),
                ('user_y', models.TextField(blank=True, max_length=200, null=True)),
                ('user_operator', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='varaiables',
        ),
    ]
